dist: trusty
sudo: required
language: node_js
node_js:
  - "node"
compiler:
  - gcc
  - clang
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
before_script:
  - npm install -g ethereumjs-testrpc
  - npm install -g truffle
script:
- testrpc &
- truffle test
